services:
    kopia:
        image: kopia/kopia:latest
        hostname: Hostname
        container_name: kopia
        restart: unless-stopped
        ports:
            - 51515:51515
        # Setup the server that provides the web gui
        env_file: .env
        command:
            - server
            - start
            - --disable-csrf-token-checks
            - --insecure
            - --address=0.0.0.0:51515
            - --server-username=admin
            - --server-password=${WEB_PASSWORD}
        volumes:
            # Mount local folders needed by kopia
            - ./config:/app/config
            - ./cache:/app/cache
            - ./logs:/app/logs
            # Mount local folders to snapshot
            - /opt/stacks:/data:ro
            # Mount repository location
            - /mnt/usb:/repository:rw
            # Mount path for browsing mounted snaphots
            - /tmp:/tmp:shared
        networks:
            - homepage_default

networks:
  homepage_default:
    driver: bridge
    external: true
