services:
  unbound:
    image: mvance/unbound-rpi:latest
    container_name: unbound
    ports:
      - "5335:53/udp"
      - "5335:53/tcp"
    restart: always
    deploy:
      replicas: 1
    environment:
      - DETACH=true