services:
  unbound:
    image: mvance/unbound-rpi:latest
    container_name: unbound
    ports:
      - "5335:53/udp"
      - "5335:53/tcp"
    restart: unless-stopped
    deploy:
      replicas: 1
    environment:
      - DETACH=true
    networks:
      - pihole_default

networks:
  pihole_default:
    external: true
