---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Information:
    - My Raspberry Pi:
        widget:
            type: glances
            url: {{HOMEPAGE_VAR_GLANCES_URL_1}}
            metric: info
            refreshInterval: 30000
    
    - CPU Temperature:
        widget:
            type: glances
            url: {{HOMEPAGE_VAR_GLANCES_URL_1}}
            metric: sensor:cpu_thermal 0
            refreshInterval: 60000
            pointsLimit: 50 # optional, defaults to 15


- Admin:
    - Portainer:
        icon: portainer.svg
        href: {{HOMEPAGE_VAR_PORTAINER_URL_1}}
        description: Docker environment manager
        server: my-docker
        container: portainer
        widget:
            type: portainer
            url: {{HOMEPAGE_VAR_PORTAINER_URL_2}}
            env: 2
            key: {{HOMEPAGE_VAR_PORTAINER_API_KEY}}
    
    - Kopia:
        icon: kopia.svg
        href: {{HOMEPAGE_VAR_KOPIA_URL_1}}
        description: Backup tool
        server: my-docker
        container: kopia
        widget:
            type: kopia
            url: {{HOMEPAGE_VAR_KOPIA_URL_2}}
            username: {{HOMEPAGE_VAR_KOPIA_USERNAME}}
            password: {{HOMEPAGE_VAR_KOPIA_PASSWORD}}

- Networking:
    - Pi-Hole:
        icon: pi-hole.svg
        href: {{HOMEPAGE_VAR_PIHOLE_URL_1}}
        description: DNS Server and Ads sinkhole
        server: my-docker
        container: pihole
        widget:
            type: pihole
            url: {{HOMEPAGE_VAR_PIHOLE_URL_2}}
            version: 5
            key: {{HOMEPAGE_VAR_PIHOLE_API_KEY}}
    
    - Unbound:
        icon: https://i.imgur.com/5IFcN3G.png
        description: Recursive DNS resolver
        server: my-docker
        container: unbound

- Utilities:
    - Watchtower:
        icon: watchtower.png
        description: Automated container updater
        server: my-docker # The docker server that was configured
        container: watchtower # The name of the container you'd like to connect
        widget:
            type: watchtower
            url: {{HOMEPAGE_VAR_WATCHTOWER_URL_1}}
            key: {{HOMEPAGE_VAR_WATCHTOWER_TOKEN}}
    
    - Glances:
        icon: glances.png
        href: {{HOMEPAGE_VAR_GLANCES_URL_2}}
        description: Monitoring tool for my Pi
        server: my-docker
        container: glances
        widget:
            type: glances
            url: {{HOMEPAGE_VAR_GLANCES_URL_1}}
            metric: cpu
            refreshInterval: 30000 # optional - in milliseconds, defaults to 1000 or more, depending on the metric
            pointsLimit: 50 # optional, defaults to 15

    - RPi-Monitor:
        icon: raspberrypi.svg
        href: {{HOMEPAGE_VAR_RPIMONITOR_URL}}
        description: Monitoring tool for my Pi
        server: my-docker
        container: rpi-monitor
