---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: My Raspberry Pi

background:
  image: /images/background.jpg
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100

headerStyle: boxed

useEqualHeights: true

layout:
  Networking:
    header: true
    style: row
    columns: 4
  Docker:
    header: true
    style: row
    columns: 4
  Utilities:
    header: true
    style: row
    columns: 4